### PR TITLE
Add method for swapping labels

### PR DESCRIPTION
**Pull request by pawel-czyz**

### CODE REVIEW

**Comment by gordonkoehn** [comment]
I'm happy to see you're rebuilding SCITE for the second time. It's so cool to see it in Rust! I'm currently learning a Rust derivative called Move myself ;)

**Comment by pawel-czyz** [comment]
> I'm happy to see you're rebuilding SCITE for the second time. It's so cool to see it in Rust! I'm currently learning a Rust derivative called Move myself ;)

@gordonkoehn 

Hi Gordon, good call! The documentation is very scarce at the moment, but you're right: the idea is to build a modular ecosystem for sampling trees in Rust (in the best case including SCITE, infSCITE, SCICONE, COMPASS, etc.). As you remember, the main issue with using JAX (which includes SMC from BlackJAX) for models beyond SCITE was the issue with the space of the trees that needed to be represented using arrays of different sizes. While for e.g., infSCITE this can *probably* still be doable, I have no idea how to efficiently implement SCICONE and COMPASS in JAX.

The two alternatives we considered back then were:
  - [Blang](https://www.stat.ubc.ca/~bouchard/blang/), which is a full probabilistic programming language, but (at least at that time) didn't support SCITE. I.e., some Java development would be required.
  - Julia-based solutions, which would be based around [Pigeons.jl](https://github.com/Julia-Tempering/Pigeons.jl) and [Turing.jl](https://turing.ml/). That would be pretty cool, but it still (a) requires implementation of the moves and (b) Julia doesn't communicate that well with Python.

So I decided to use it as an opportunity to finally get started with Rust. The idea would be then:

  - Generic `Tree` structure together with the tree moves, which can underlie all of mentioned models for reconstructing phylogenies. (And allow one to build other models, perhaps based around e.g., scRNA-seq or even scATAC-seq data?)
  - Generic MCMC moves for low-dimensional continuous parameters.
  - A generic Sequential Monte Carlo sampler, which can take advantage of Rust's multithreading.
  - Rust has excellent Python support thanks to [Maturin](https://www.maturin.rs/), so that e.g., visualisation, convergence checks and other complex data analysis tasks could be handled in Python (or Snakemake).

(Of course, another alternative would be (modern) C++. However, most of the already developed code wasn't built around abstractions suitable for building SMC samplers, so that probably wouldn't give much time difference over implementing these abstractions from scratch.)

If this project were successful, we would have something like a Rust-based BlackJAX ("BlackForest"?): you construct a Rust-based loglikelihood taking the tree and the parameters, choose one of the highly-parallelized samplers in Rust and then you obtain a posterior over trees.
However, I guess that (a) the project may fail for a lot of reasons in between and (b) even if it didn't fail, it'd still several months of work before it even looks somewhat usable :wink: So I'm treating it right now just as an opportunity to learn more Rust. Glad you're learning it as well!

**Comment by gordonkoehn** [comment]
Yes, I remember the other paths we could have taken and their merits. Thanks for sharing your reasoning on what you are building here - I am always learning how languages/packages fit together from you! Always a pleasure!  Whatever the project turns into, I'll be watching with excitement.  😊

**Comment by pawel-czyz** [comment]
Thanks a lot! :blush:

**Pull request merged**
